# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Puzh-Iti5SIOYayQzSFaWX90QLXWGJIU

### Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

"""### Load Dataset dari GitHub"""

url = "https://raw.githubusercontent.com/Evameivina/Renewable-Energy-/main/energy_dataset_.csv"
df = pd.read_csv(url)

print("=== Cek dan Hapus Duplikat ===")
duplicate_count = df.duplicated().sum()
print("Jumlah duplikat:", duplicate_count)
df = df.drop_duplicates()

"""### Data Understanding"""

print("=== Sample Data ===")
print(df.head())

print("\n=== Data Info ===")
df.info()

print("\n=== Descriptive Statistics ===")
print(df.describe())

"""### Data Preparation"""

# Bersihkan nama kolom
df.columns = [col.strip() for col in df.columns]

# Handle missing values
df.fillna(0, inplace=True)

# Mapping kode numerik ke kategori
energy_map = {1: "Solar", 2: "Wind", 3: "Hydroelectric", 4: "Geothermal",
              5: "Biomass", 6: "Tidal", 7: "Wave"}
grid_map = {1: "Fully Integrated", 2: "Partially Integrated",
            3: "Minimal Integration", 4: "Isolated Microgrid"}
funding_map = {1: "Government", 2: "Private", 3: "Public-Private Partnership"}

df['Type_of_Renewable_Energy'] = df['Type_of_Renewable_Energy'].map(energy_map)
df['Grid_Integration_Level'] = df['Grid_Integration_Level'].map(grid_map)
df['Funding_Sources'] = df['Funding_Sources'].map(funding_map)

fokus_cols = ['Type_of_Renewable_Energy',
              'Energy_Production_MWh', 'Energy_Consumption_MWh',
              'Initial_Investment_USD', 'GHG_Emission_Reduction_tCO2e',
              'Air_Pollution_Reduction_Index', 'Funding_Sources']
df = df[fokus_cols]

# Visualisasi Fokus 1: Tren Produksi & Konsumsi Energi
plt.figure(figsize=(12,6))
for energy in df['Type_of_Renewable_Energy'].unique():
    temp = df[df['Type_of_Renewable_Energy'] == energy]
    plt.plot(temp['Energy_Production_MWh'].values, label=f"{energy} Production")
    plt.plot(temp['Energy_Consumption_MWh'].values, label=f"{energy} Consumption")

plt.xlabel("Record Index")
plt.ylabel("MWh")
plt.title("Energy Production vs Consumption per Type")
plt.legend()
plt.show()

# Forecasting sederhana untuk satu jenis energi (misal Solar)
forecast_energy = "Solar"
forecast_df = df[df['Type_of_Renewable_Energy'] == forecast_energy]
X = np.array(range(len(forecast_df))).reshape(-1,1)
y = forecast_df['Energy_Production_MWh'].values
model = LinearRegression()
model.fit(X, y)
future_index = np.array(range(len(X), len(X)+5)).reshape(-1,1)
y_pred_future = model.predict(future_index)
print(f"Prediksi produksi {forecast_energy} 5 periode ke depan:", y_pred_future)

# Visualisasi Fokus 2: Investasi & Dampak Lingkungan
sns.set(style="whitegrid", palette="muted", font_scale=1.1)

# Scatter plot: Investment vs GHG Emission Reduction
plt.figure(figsize=(10,6))
sns.scatterplot(data=df,
                x='Initial_Investment_USD',
                y='GHG_Emission_Reduction_tCO2e',
                hue='Type_of_Renewable_Energy',
                style='Funding_Sources',
                s=100)
plt.xlabel("Initial Investment (USD)")
plt.ylabel("GHG Emission Reduction (tCO2e)")
plt.title("Investment vs GHG Emission Reduction")
plt.show()

